include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - example/**
    - lib/third_party/**     # may not be fully migrated
    - lib/src/generated_bindings.dart # ignore generated files
