include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - example/**
    - lib/cronet_sample.dart # due to method channel
    - lib/third_party/**
linter:
  rules:
    - directives_ordering
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_brace_in_string_interps
