name: cronet_sample
description: A cronet based HTTP Library sample.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  ffigen: ^2.4.0

ffigen:
  name: 'Cronet'
  description: 'Bindings to Cronet'
  output: 'lib/src/generated_bindings.dart'
  array-workaround: true
  headers:
    entry-points:
      - 'lib/src/wrapper/wrapper.h'
    include-directives:
      - 'lib/src/wrapper/wrapper.h'
      - 'dart_api.h'
      - 'dart_native_api.h'
      - 'dart_api_dl.h'
      - 'lib/src/wrapper/wrapper_export.h'
  compiler-opts:
    - '-I/usr/lib/dart/include/ -DDART_SHARED_LIB'
