name: cronet_sample
description: A cronet based HTTP Library sample.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  # flutter: ">=1.20.0"

dependencies:
  # flutter:
  #   sdk: flutter
  ffi: ^1.0.0
  path: any

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  pedantic: ^1.11.0
  ffigen: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.cronet_sample
        pluginClass: CronetSamplePlugin
      linux:
        pluginClass: CronetSamplePlugin


ffigen:
  name: 'Cronet'
  description: 'Bindings to Cronet'
  output: 'lib/src/generated_bindings.dart'
  array-workaround: true
  headers:
    entry-points:
      - 'lib/src/native/wrapper/wrapper.h'
    include-directives:
      - 'lib/src/native/wrapper/wrapper.h'
      - 'dart_api.h'
      - 'dart_native_api.h'
      - 'dart_api_dl.h'
      - 'lib/src/native/wrapper/wrapper_export.h'
  compiler-opts:
    - '-Ilib/src/native/include/ -DDART_SHARED_LIB'
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
